<?php

namespace SIT\PlatformBundle\Repository;

/**
 * EtatProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
